# Generated by Django 4.2.1 on 2023-05-31 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alter_product_created'),
        ('auctions', '0003_product_price'),
    ]

    operations = [
    ]
