# Generated by Django 4.2.1 on 2023-06-01 09:41

import auctions.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_merge_0002_alter_product_created_0003_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='winner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=models.SET(auctions.models.Product.get_user), related_name='winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
